--CREATE DATABASE MobileShop

-- Sozdaniye
use MobileShop
CREATE TABLE Phones (
ID INT NOT NULL PRIMARY KEY,
Model VARCHAR(50) NOT NULL,
Manufacturer VARCHAR(50) NOT NULL,
Color VARCHAR(20) NOT NULL,
Specs VARCHAR(MAX),
Price DECIMAL(10,2) NOT NULL,
TotalSales DECIMAL(10, 2) NOT NULL
);


CREATE TABLE Customers (
ID INT NOT NULL PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Address VARCHAR(100),
Phone VARCHAR(20) NOT NULL
);

CREATE TABLE Orders (
ID INT NOT NULL PRIMARY KEY,
OrderDate DATETIME NOT NULL,
CustomerID INT NOT NULL,
Quantity INT NOT NULL,
TotalPrice DECIMAL(10,2) NOT NULL,
Status VARCHAR(20) NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES Customers(ID)
);

CREATE TABLE Sales (
ID INT NOT NULL PRIMARY KEY,
SaleDate DATETIME NOT NULL,
PhoneID INT NOT NULL,
Quantity INT NOT NULL,
Price DECIMAL(10,2) NOT NULL,
FOREIGN KEY (PhoneID) REFERENCES Phones(ID)
);


CREATE TABLE Suppliers (
ID INT NOT NULL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Address VARCHAR(100),
Phone VARCHAR(20) NOT NULL
);



